version: '3.5'
services:
    firmware:
        build: firmware
        container_name: firmware_container # used by server
        entrypoint: 'true' # stub command
        image: firmware_image # used by server
        volumes:
            - './.git:/.git:ro'
            - './firmware:/firmware:ro'
            - './out:/out:rw'
    server:
        build: server
        depends_on:
            - firmware
        devices:
            - '${CRAZYRADIO}'
        environment:
            - 'CF2_BIN=/out/cf2.bin'
        networks:
            - olympus
        ports:
            - '5000:5000' # access from host
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock:rw'

            - './firmware:/firmware:rw' # sandbox/src/main.cpp
            - './out:/build/out:ro'

            - './server:/server:ro'
            - './server/data:/build/data:rw'
    dashboard:
        build: dashboard
        depends_on:
            - server
        ports:
            - '4200:4200' # access from host
        volumes:
            - './dashboard:/dashboard:ro'
    simulation:
        build: simulation
        depends_on:
            - server
        environment:
            - 'HOST=server'
            - 'LAUNCH_ARG=${LAUNCH_ARG}'
            - 'QT_QPA_PLATFORM=wayland'
            - 'WAYLAND_DISPLAY=${WAYLAND_DISPLAY}'
            - 'XDG_RUNTIME_DIR=/tmp'
        networks:
            - olympus
        volumes:
            - '${XDG_RUNTIME_DIR}/${WAYLAND_DISPLAY}:/tmp/${WAYLAND_DISPLAY}:ro'
            - './simulation:/simulation:ro'
networks:
    olympus:
